config/routes.rb
Rails.application.routes.draw do
  root "main#index"
  get "admin", to: "admin#index"

  get "signup", to: "signup#new"
  post "signup", to: "signup#create"

  get "signin", to: "sessions#new"
  post "signin", to: "sessions#create"

  get "logout", to: "sessions#destroy"

  get "password", to: "password#edit"
  patch "password", to: "password#update"

  get "cart", to: "cart#index"
  post "cart", to: "cart#add_product"
  delete "cart", to: "cart#delete"

  get "product/:id/edit", to: "product#edit", as: "edit_product"
  patch "product/:id/", to: "product#update", as: "update_product"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  validates :product_id, presence: true
  belongs_to :user
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, presence: true
  validates :price, presence: true
  validates :quantity, presence: true
  validates :description, presence: true, length: {minimum: 10 , maximum: 100}
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :username, presence: true
  has_many :cart_items

  def calculate_total 
    self.cart_items.map {|item| item[:price] * item[:quantity]}.sum()
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :require_user_logged_in

  def index
    @products = Product.all
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
before_action :require_user_logged_in
skip_before_action :verify_authenticity_token, only: [:add_product]

  def index
    @cart_items = Current.user.cart_items
  end

  def add_product
    user = User.find(Current.user[:id])
    product = Product.find(params[:product_id])
    product_quantity = product[:quantity]
    product.update({quantity: product_quantity - 1})
    cart_item = Current.user.cart_items.find_by(product_id: product[:id])

    if (cart_item)
      quantity = cart_item[:quantity]
      cart_item.update({quantity: quantity + 1})
      redirect_to root_path, notice: "Product already in cart. Quantity updated."
    else
      new_cart_item = user.cart_items.new({name: product.name, price: product.price, quantity: 1, product_id: product[:id]})

      if (new_cart_item.save())
        redirect_to root_path, notice: "Product added successfully."
      else
        redirect_to root_path, alert: "Unable to add product."
      end
    end
  end

  def delete
    quantity = Current.user.cart_items.find_by(product_id: params[:product_id])[:quantity]
    if (Current.user.cart_items.delete_by(product_id: params[:product_id]))
      product = Product.find(params[:product_id])
      product_quantity = product[:quantity]
      product.update({quantity: product_quantity + quantity})
      redirect_to cart_path, notice: "Product removed successfully."
    else
      redirect_to cart_path, alert: "Unable to remove product."
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @products = Product.all()
  end
end

app/controllers/password_controller.rb
class PasswordController < ApplicationController
  before_action :require_user_logged_in

  def edit
  end

  def update
    if Current.user.update(password_params)
      redirect_to root_path, notice: "Password updated successfully"
    else
      redirect_to password_path, alert: "Password update unsuccessfull. Please try again"
    end
  end

  private
  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  def edit
    @product = Product.find(params[:id])
  end

  def update
    product = Product.find(params[:id])
    if (product.update(product_params))
      redirect_to admin_path, notice: "Product updated successfully."
    else
      redirect_to admin_path, notice: "Unable to update product."
    end
  end

  private
  def product_params
    params.require(:product).permit(:name, :price, :quantity, :description)
  end
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
  def new
    @user = User.new()
  end

  def create
    if (User.find_by(username: params[:user][:username]))
      redirect_to root_path, alert: "Username already exists. Please try another username."
    else
      @user = User.new(user_params)

      if (@user[:username] == "admin")
        redirect_to root_path, alert: "You can not create Admin account."
      else
        if (@user.save())
          session[:user_id] = @user.id
          redirect_to root_path, notice: "Signed Up successfull."
        else
          render :new, alert: "Unable to Sign Up. Please try again."
        end
      end
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/password_helper.rb
module PasswordHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/views/admin/index.html.erb
<div class="container">
  <h1>Welcome to Admin Dashboard</h1>

  <div class="d-sm-flex align-items-center justify-content-start flex-wrap">
    <% @products.each do |product| %>
      <div class="card bg-dark text-light w-25 align-self-center m-3">
        <div class="card-body text-center">
          <h1 class="card-title mb-3">
            <%= product[:name] %>
          </h1>
          <div class="h3 mb-3">
            ₹<%= product[:price] %>
          </div>
              <p class="card-text">
                <%= product[:description] %>
              </p>
          <%= link_to "Update Product", edit_product_path(product), class: "btn btn-outline-light" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shopping Cart</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css">
    <script src="	https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
      <%= render "shared/navbar" %>
      <%= render "shared/flash" %>
      <%= yield %>
  </body>
</html>

app/views/shared/_flash.html.erb
<div class="container">
  <% if flash.now[:notice] %>
    <div class="alert alert-primary alert-dismissible fade show mt-2" role="alert">
      <%= flash.now[:notice] %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
  <% if flash.now[:alert] %>
    <div class="alert alert-warning alert-dismissible fade show mt-2" role="alert">
      <%= flash.now[:alert] %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>  

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-dark test-white py-3">
  <div class="container">
    <div class="navbar-brand text-white">RAILS</div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar">
      <span class="navbar-toggler-icon text-white"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbar">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if Current.user && Current.user[:username] == "admin" %>
          <li class="nav-item">
            <%= link_to "Home", admin_path, class: "nav-link text-white" %>
          </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Home", root_path, class: "nav-link text-white" %>
            </li>
          <% end %>
        <% if Current.user %>
          <% if Current.user[:username] != "admin" %>
            <li class="nav-item">
              <%= link_to "Cart", cart_path, class: "nav-link text-white" %>
            </li>
          <% end %>
        <% end %>
      </ul>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if Current.user %>
          <li class="nav-item">
            <%= link_to "Change Password", password_path, class: "btn btn-outline-light mx-3" %>
          </li>
          <li class="nav-item">
            <%= link_to "Logout", logout_path, class: "btn btn-light" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign In", signin_path, class: "btn btn-outline-light mx-3" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", signup_path, class: "btn btn-outline-light" %>
          </li>
        <%end%>
      </ul>
    </div>
  </div>
</nav>