config/routes.rb
Rails.application.routes.draw do
  root "main#index"
  get "admin", to: "admin#index"

  get "signup", to: "signup#new"
  post "signup", to: "signup#create"

  get "signin", to: "sessions#new"
  post "signin", to: "sessions#create"

  get "logout", to: "sessions#destroy"

  get "password", to: "password#edit"
  patch "password", to: "password#update"

  get "cart", to: "cart#index"
  post "cart", to: "cart#add_product"
  delete "cart", to: "cart#delete"

  get "product/:id/edit", to: "product#edit", as: "edit_product"
  patch "product/:id/", to: "product#update", as: "update_product"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  validates :product_id, presence: true
  belongs_to :user
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, presence: true
  validates :price, presence: true
  validates :quantity, presence: true
  validates :description, presence: true, length: {minimum: 10 , maximum: 100}
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :username, presence: true
  has_many :cart_items

  def calculate_total 
    self.cart_items.map {|item| item[:price] * item[:quantity]}.sum()
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :require_user_logged_in

  def index
    @products = Product.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user

  def set_current_user
    if (session[:user_id])
      Current.user = User.find_by(id: session[:user_id])
    end
  end

  def require_user_logged_in
    redirect_to signin_path, alert: "You must be signed in. " if Current.user.nil?
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
before_action :require_user_logged_in
skip_before_action :verify_authenticity_token, only: [:add_product]

  def index
    @cart_items = Current.user.cart_items
  end

  def add_product
    user = User.find(Current.user[:id])
    product = Product.find(params[:product_id])
    product_quantity = product[:quantity]
    product.update({quantity: product_quantity - 1})
    cart_item = Current.user.cart_items.find_by(product_id: product[:id])

    if (cart_item)
      quantity = cart_item[:quantity]
      cart_item.update({quantity: quantity + 1})
      redirect_to root_path, notice: "Product already in cart. Quantity updated."
    else
      new_cart_item = user.cart_items.new({name: product.name, price: product.price, quantity: 1, product_id: product[:id]})

      if (new_cart_item.save())
        redirect_to root_path, notice: "Product added successfully."
      else
        redirect_to root_path, alert: "Unable to add product."
      end
    end
  end

  def delete
    quantity = Current.user.cart_items.find_by(product_id: params[:product_id])[:quantity]
    if (Current.user.cart_items.delete_by(product_id: params[:product_id]))
      product = Product.find(params[:product_id])
      product_quantity = product[:quantity]
      product.update({quantity: product_quantity + quantity})
      redirect_to cart_path, notice: "Product removed successfully."
    else
      redirect_to cart_path, alert: "Unable to remove product."
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @products = Product.all()
  end
end

app/controllers/password_controller.rb
class PasswordController < ApplicationController
  before_action :require_user_logged_in

  def edit
  end

  def update
    if Current.user.update(password_params)
      redirect_to root_path, notice: "Password updated successfully"
    else
      redirect_to password_path, alert: "Password update unsuccessfull. Please try again"
    end
  end

  private
  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  def edit
    @product = Product.find(params[:id])
  end

  def update
    product = Product.find(params[:id])
    if (product.update(product_params))
      redirect_to admin_path, notice: "Product updated successfully."
    else
      redirect_to admin_path, notice: "Unable to update product."
    end
  end

  private
  def product_params
    params.require(:product).permit(:name, :price, :quantity, :description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:username])

    if (user.present? && user.authenticate(params[:password]))
      session[:user_id] = user.id
      if (user[:username] == "admin")
        redirect_to admin_path, notice: "Signed In successfully."
      else
        redirect_to root_path, notice: "Signed In successfully."
      end
    else
      redirect_to signin_path, alert: "Invalid Username or Password"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged Out"
  end
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
  def new
    @user = User.new()
  end

  def create
    if (User.find_by(username: params[:user][:username]))
      redirect_to root_path, alert: "Username already exists. Please try another username."
    else
      @user = User.new(user_params)

      if (@user[:username] == "admin")
        redirect_to root_path, alert: "You can not create Admin account."
      else
        if (@user.save())
          session[:user_id] = @user.id
          redirect_to root_path, notice: "Signed Up successfull."
        else
          render :new, alert: "Unable to Sign Up. Please try again."
        end
      end
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/password_helper.rb
module PasswordHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/views/cart/index.html.erb
<div class="container py-2">
  <h1>Your Cart:</h1>
  <h2>Total Products: <%= @cart_items.length %></h2>
  <h2>Total Amount: <%= Current.user.calculate_total %></h2>
  <div class="d-sm-flex align-items-center justify-content-even flex-wrap">
    <% @cart_items.each do |item| %>
      <div class="card bg-dark text-light w-25 align-self-center m-2">
        <div class="card-body text-center">
          <h1 class="card-title mb-3">
            <%= item[:name] %>
          </h1>
          <div class="h3 mb-3">
            ₹<%= item[:price] %>
          </div>
              <p class="card-text">
                Quantity: <%= item[:quantity] %>
              </p>
          <%= button_to "Delete", {:controller => "cart", :action => "delete", product_id: item[:product_id]}, :method => :delete, class: "btn btn-outline-light" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/main/index.html.erb
<div class="container py-2">
  <h1>Welcome to shopping cart</h1>

  <div class="d-sm-flex align-items-center justify-content-start flex-wrap">
    <% @products.each do |product| %>
      <div class="card bg-dark text-light w-25 align-self-center m-3">
        <div class="card-body text-center">
          <h1 class="card-title mb-3">
            <%= product.name %>
          </h1>
          <div class="h3 mb-3">
            ₹<%= product.price %>
          </div>
          <p class="card-text fw-bold">
            Available qantity: <%= product.quantity %>
          </p>
          <p class="card-text">
            <%= product.description %>
          </p>
          <%= button_to "Add to Cart", {:controller => "cart", :action => "add_product", product_id: product[:id]}, class: "btn btn-outline-light" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<%# <script>
  addButtons = document.querySelectorAll(".add-to-cart")
  addButtons.forEach (addButton => {
    addButton.addEventListener("click", e => {addToCart(e)})
  })

  function addToCart(e) {
    quantity = prompt("Enter the quantity.")
    id = (e.target.value)
    console.log(id)
    console.log(quantity)

    var http = new XMLHttpRequest()
    http.open("POST", `/cart?product_id=${id}&quantity=${quantity}`, true)
    http.send()
  }
</script> %>

app/views/password/edit.html.erb
<div class="container">
  <h1>Change Password</h1>

  <%= form_with model: Current.user, url: password_path do |form| %>
    <div class="mb-3">
      <%= form.label :password, class: "form-label" %>
      <%= form.password_field :password, class: "form-control", placeholder: "password" %>
    </div>
    <div class="mb-3">
      <%= form.label :password_confirmation, class: "form-label" %>
      <%= form.password_field :password_confirmation, class: "form-control", placeholder: "password" %>
    </div>
    <%= form.submit "Update Password", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/product/edit.html.erb
<div class="container py-2">
  <%= form_with model: @product, url: update_product_path(@product) do |form| %>
    <div class="mb-3">
      <%= form.label :name, class: "form-label" %>
      <%= form.text_field :name, class: "form-control", placeholder: "Product Name" %>
    </div>
    <div class="mb-3">
      <%= form.label :price, class: "form-label" %>
      <%= form.number_field :price, class: "form-control", placeholder: "Product Price (should be number.)" %>
    </div>
    <div class="mb-3">
      <%= form.label :quantity, class: "form-label" %>
      <%= form.number_field :quantity, class: "form-control", placeholder: "Product Quantity (should be integer)"%>
    </div>
    <div class="mb-3">
      <%= form.label :description, class: "form-label" %>
      <%= form.text_area :description, class: "form-control", placeholder: "Product Description" %>
    </div>
    <%= form.submit "Save changes", class: "btn btn-dark" %>
  <% end %>
</div>

app/views/signup/new.html.erb
<div class="container">
  <h1>Sign Up</h1>

  <%= form_with model: @user, url: signup_path do |form| %>
    <div class="mb-3">
      <%= form.label :username, class: "form-label"%>
      <%= form.text_field :username, class: "form-control", placeholder: "Username" %>
    </div>
    <div class="mb-3">
      <%= form.label :password, class: "form-label" %>
      <%= form.password_field :password, class: "form-control", placeholder: "password" %>
    </div>
    <div class="mb-3">
      <%= form.label :password_confirmation, class: "form-label" %>
      <%= form.password_field :password_confirmation, class: "form-control", placeholder: "password" %>
    </div>
    <%= form.submit "Sign up", class: "btn btn-primary" %>
  <% end %>
</div>